#! /bin/sh

FIRST_DESK=I
REMAINING_DESKS="II III IV V"

bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

bspc config split_ratio             0.52
bspc config border_width            3
bspc config window_gap              12
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config focused_border_color    '#FFBB00'
bspc config normal_border_color     '#6E6E6E'

bspc rule -a feh --floating
bspc rule -a Gimp --floating
bspc rule -a Steam --floating
bspc rule -a MPlayer --floating
bspc rule -a Mumble --floating
bspc rule -a VirtualBox --floating
